# Default values for ngrok.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: stefanprodan/ngrok
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4040

expose:
  service: teleport:3080
#  service: ga-podinfo:9898

# https://gravitational.com/teleport/docs/admin-guide/#ports
tunnels:
  proxy-ssh:
    addr: teleport:3023
    proto: tcp
  proxy-tunnel:
    addr: teleport:3024
    proto: tcp
  auth:
    addr: teleport:3025
    proto: tcp
  proxy-web:
    addr: teleport:3080
    proto: http

token: placeyourauthtokenhere

nodeSelector: {}

tolerations: []

affinity: {}
